company_urls = [
    "https://job-boards.eu.greenhouse.io/bvnk",
    "https://www.1nebula.com/development",
    "https://www.acrontum.com/careers/",
    "https://www.afrihost.com/careers",
    "https://spandigital.com/working-at-span/",
    "https://jobs.cisco.com/jobs/SearchJobs/?21178=%5B215431%5D&21178_format=6020&listFilterMode=1",
    "https://www.clickatell.com/jobs/jobs-listing/",
    "https://www.digicert.com/careers",
    "https://dvtcareers.recruitee.com/",
    "https://gadventures.wd3.myworkdayjobs.com/GAdventures?locations=e89ea7ddd373011868c94e9c1af60000&locations=e89ea7ddd373011868c960ad9ce40000",
    "https://careers.ghost.org/",
    "https://careers.ioco.tech/index/?sortBy=DPOSTINGSTART&sortOrder=desc",
    "https://www.kingmakers.com/careers/",
    "https://meltwatercareers.ttcportals.com/search/jobs/in/cape-town",
    "https://kurtosys.bamboohr.com/careers",
    "https://bbdsoftware.com/open-positions/#positions",
    "https://careers.jumo.world/all-jobs/",
    "https://www.accenture.com/za-en/careers/jobsearch?jk=&sb=1&vw=1&is_rj=0&pg=1",
    "https://externalcareers.ninetyone.com/experienced-hires/",
    "https://www.standardbank.com/sbg/standard-bank-group/careers/apply/jobs/view-all-jobs",
    "https://jobs.nedbank.co.za/search/?createNewAlert=false&q=&locationsearch=cape+town",
    "https://career2.successfactors.eu/career?company=allangrayp&career_ns=job_listing_summary&navBarLevel=JOB_SEARCH&rcm_site_locale=en_GB&selected_lang=en_GB",
    "https://careers.luno.com/jobs/?search=&location=Cape+Town",
    "https://jobs.vodafone.com/careers?start=0&location=Cape+Town%2C++South+Africa&pid=563018685719727&sort_by=distance&filter_distance=80&filter_include_remote=1",
    "https://ehle.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?location=Cape+Town%2C+Western+Cape%2C+South+Africa&locationId=300000016298453&locationLevel=city&mode=location&radius=25&radiusUnit=MI",
    "https://www.sanlamonline.co.za/careers/job-listing/",
    "https://www.monoclesolutions.com/en-za/careers/experienced-professionals",
    "https://oldmutual.wd3.myworkdayjobs.com/Old_Mutual_Careers?locationCountry=4db3c26940b944919b83612cc1193eed&locations=d63f384672ac016b0eb73b431504d2ad",
    "https://careers.yoco.com/jobs?location=Cape+Town+%28South+Africa%29&split_view=true&query=",
    "https://careers.bcx.co.za/search/?createNewAlert=false&q=&locationsearch=cape+town",
    "https://altron.wd3.myworkdayjobs.com/Altron_Careers/?locations=994dd852d2a301c47b34826ffe00b33a&locations=994dd852d2a30160b860366ffe000b3a&locations=994dd852d2a3014be088b66ffe005b3b",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
]
