company_urls = [
    "https://job-boards.eu.greenhouse.io/bvnk",
    "https://www.1nebula.com/development",
    "https://www.acrontum.com/careers/",
    "https://www.afrihost.com/careers",
    "https://spandigital.com/working-at-span/",
    "https://jobs.cisco.com/jobs/SearchJobs/?21178=%5B215431%5D&21178_format=6020&listFilterMode=1",
    "https://www.clickatell.com/jobs/jobs-listing/",
    "https://www.digicert.com/careers",
    "https://dvtcareers.recruitee.com/",
    "https://gadventures.wd3.myworkdayjobs.com/GAdventures?locations=e89ea7ddd373011868c94e9c1af60000&locations=e89ea7ddd373011868c960ad9ce40000",
    "https://careers.ghost.org/",
    "https://careers.ioco.tech/index/?sortBy=DPOSTINGSTART&sortOrder=desc",
    "https://www.kingmakers.com/careers/",
    "https://meltwatercareers.ttcportals.com/search/jobs/in/cape-town",
    "https://kurtosys.bamboohr.com/careers",
    "https://bbdsoftware.com/open-positions/#positions",
    "https://careers.jumo.world/all-jobs/",
    "https://www.accenture.com/za-en/careers/jobsearch?jk=&sb=1&vw=1&is_rj=0&pg=1",
    "https://externalcareers.ninetyone.com/experienced-hires/",
    "https://www.standardbank.com/sbg/standard-bank-group/careers/apply/jobs/view-all-jobs",
    "https://jobs.nedbank.co.za/search/?createNewAlert=false&q=&locationsearch=cape+town",
    "https://career2.successfactors.eu/career?company=allangrayp&career_ns=job_listing_summary&navBarLevel=JOB_SEARCH&rcm_site_locale=en_GB&selected_lang=en_GB",
    "https://careers.luno.com/jobs/?search=&location=Cape+Town",
    "https://jobs.vodafone.com/careers?start=0&location=Cape+Town%2C++South+Africa&pid=563018685719727&sort_by=distance&filter_distance=80&filter_include_remote=1",
    "https://ehle.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?location=Cape+Town%2C+Western+Cape%2C+South+Africa&locationId=300000016298453&locationLevel=city&mode=location&radius=25&radiusUnit=MI",
    "https://www.sanlamonline.co.za/careers/job-listing/",
    "https://www.monoclesolutions.com/en-za/careers/experienced-professionals",
    "https://oldmutual.wd3.myworkdayjobs.com/Old_Mutual_Careers?locationCountry=4db3c26940b944919b83612cc1193eed&locations=d63f384672ac016b0eb73b431504d2ad",
    "https://careers.yoco.com/jobs?location=Cape+Town+%28South+Africa%29&split_view=true&query=",
    "https://careers.bcx.co.za/search/?createNewAlert=false&q=&locationsearch=cape+town",
    "https://altron.wd3.myworkdayjobs.com/Altron_Careers/?locations=994dd852d2a301c47b34826ffe00b33a&locations=994dd852d2a30160b860366ffe000b3a&locations=994dd852d2a3014be088b66ffe005b3b",
    "https://www.snapscan.co.za/about#careers",
    "https://campaign.sweepsouth.com/careers/?gad_source=1&gad_campaignid=20808985859&gbraid=0AAAAADnJHjEF_HbUoqxpbtIXXAlwiSwCy&gclid=CjwKCAjw24vBBhABEiwANFG7y-3vnD_8_u_UoDuWH_QkFnc9Py3x1TQM61m_TzTnSwKPxHevTEV8RBoC9b4QAvD_BwE#lp-pom-block-135",
    "https://www.sage.com/en-za/company/careers/career-search/?country=South%20Africa&page=1",
    "https://firstrand.wd3.myworkdayjobs.com/FRB?locationCountry=4db3c26940b944919b83612cc1193eed&primaryLocation=6450b01b9917101d4b5e7d634f190000",
    "https://careers.woolworths.co.za/applicant/index.php?controller=Page&name=jobsearch",
    "https://careers.discovery.co.za/go/All-Jobs/4509301/?q=&q2=&alertId=&locationsearch=&title=&location=Cape+Town&date=",
    "https://momentum.erecruit.co/candidateapp/Jobs/Categories/Information_Technology/e83167290f874dbda49ff2c4afb21995",
    "https://betsoftware.com/careers/cape-town/#listings",
    "https://jse.pnet.co.za/applicant/index.php?controller=Page&name=jobsearch",
    "https://jobs.telkom.co.za/search/?createNewAlert=false&q=&locationsearch=cape+town",
    "https://www.takealot.com/careers/takealot",
    "https://www.takealot.com/careers/mr-d",
    "https://fa-etyi-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/MrPriceGroupCareers/jobs?location=Cape+Town%2C+Western+Cape%2C+South+Africa&locationId=100000010713033&locationLevel=city&mode=location&radius=25&radiusUnit=MI",
    "https://www.santam.co.za/careers/jobs/",
    "https://ayo-holdings.com/careers/",
    "https://www.iqbusiness.net/careers/search-job",
    "https://www.bmwithub.co.za/opportunities.html",
    "https://csgi.wd5.myworkdayjobs.com/CSGCareers?locations=2679412f35711000b70aff54dc5232c1",
    "https://globalus251.dayforcehcm.com/CandidatePortal/en-US/gligroup/Site/GLI",
    "https://corporate.lightstone.co.za/careers",
    "https://payment24.co.za/careers/",
    "https://apply.workable.com/euromonitor/",
    "https://jobs.mercedes-benz.com/en?en%3FPositionFormattedDescription.Content=automation&PositionLocation.Country=%5B501%5D&PositionFormattedDescription.Content=%22test%22",
    "https://isometrix.breezy.hr/",
    "https://byteorbit.com/careers/",
    "https://www.entersekt.com/company/entersekt-careers",
    "https://jobs.careers.microsoft.com/global/en/search?lc=South%20Africa&l=en_us&pg=1&pgSz=20&o=Relevance&flt=true&ref=cms",
    "https://bidvestfacilitiesmanagement.simplify.hr/#currentVacanciesContainer",
    "https://jobs.ashbyhq.com/Deel?locationId=9192fc1c-17db-4541-9df5-3ba05320c8ff",
    "https://lulalend.breezy.hr/",
    "https://confluence.pinpointhq.com/#js-careers-jobs-block",
    "https://doctorly-germany.jobs.personio.de/",
    "https://jobs.lever.co/mamamoney?location=Cape%20Town%2C%20ZA",
    "https://www.ilabquality.com/career-opportunities/south-africa/",
    "https://paystack.com/careers",
    "https://mukuru.breezy.hr/?&country=South%20Africa#positions",
    "https://www.voss-solutions.com/careers/",
    "https://www.redstor.com/about-us/careers/",
    "https://careers.fdmgroup.com/vacancies/vacancy-search-results.aspx",
    "https://www.structureit.net/careers/",
    "https://scrumsdotcom.recruitee.com/",
    "https://jobs.lever.co/titanwh?location=Cape%20Town",
    "https://careers.capitecbank.co.za/search/?createNewAlert=false&q=&locationsearch=cape+town&optionsFacetsDD_title=&optionsFacetsDD_location=&optionsFacetsDD_department=",
    "https://www.lexisnexis.com/systems/careers/job-search.html?c=South%20Africa&g=Engineering%20%26%20Technology&r=10&s=0&f=Data%20Analytics%7CData%20Analytics%2FScience%20Generalist%7CData%20Discovery%20and%20Enrichment%7CData%20Mgmt%20%26%20Engineering%7CData%20Science%7CIT%20Operations%7CIT%20Program%20Management%7CQuality%20Engineering%7CSecurity%7CSite%20Reliability%20Engineering%7CSoftware%20Engineering%7CSystems%20Engineering%7CTechnology%2FSystems%20Consulting%20-%20ERP%20Applications&l=South%20Africa%20-%20Cape%20Town&k=test",
    "https://hexagon.com/company/careers/job-listings#jl_country=South%20Africa&nearme=1&jl_e=0",
    "https://careers.salesforce.com/en/jobs/?search=&country=South+Africa&pagesize=20#results",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
]
