company_urls = [
    "https://career.globant.com/?country=SP&deparment=Software+Development",
    "https://jobs.lever.co/emburse?location=Spain",
    "https://careers.datadoghq.com/all-jobs/?location_EMEA%5B0%5D=Barcelona",
    "https://www.capgemini.com/careers/join-capgemini/job-search/?keyword=test&count",
    "https://jobs.adp.com/en/jobs/?search=automation&ref=&mylocation=Spain&pagesize=20&lat=&lng=#results",
    "https://www.ibm.com/careers/search?field_keyword_05[0]=Spain",
    "https://jobs.concentrix.com/spain/job-search/?&country=Spain&keywor",
    "https://adevinta.com/careers/jobs/?job-title-keyword=&job-page=1&job-page-size=15&job-country=spain&job-city=&job-brand=&job-function=&job-time-type=",
    "https://www.nttdata.com/global/en/Careers/Search-jobs?query=barcelona",
    "https://careers.soprasteria.com/jobs?options=&page=1&q=quality%20automation&ln=&la=0&lo=0&lr=20&li=",
    "https://www.sage.com/en-za/company/careers/career-search/?country=Spain&page=1",
    "https://www.sage.com/en-za/company/careers/career-search/?country=Spain&page=2",
    "https://www.sage.com/en-za/company/careers/career-search/?country=Spain&page=3",
    "https://jobs.atos.net/search/?createNewAlert=false&q=&locationsearch=barcelona&optionsFacetsDD_country=&optionsFacetsDD_city=&optionsFacetsDD_customfield2=&optionsFacetsDD_customfield4=&optionsFacetsDD_department=",
    "https://www.betterask.erni/es-en/job-opportunities/",
    "https://careers.manomano.jobs/en-GB/jobs?location=Barcelona&split_view=true&query=",
    "https://careers.manomano.jobs/en-GB/jobs?location=Barcelona&split_view=true&query=",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
    # "",
]
