# job_keywords = [
#     "software development engineer in test",
#     "software engineer in test",
#     "software engineer, test",
#     "test engineer",
#     "test automation engineer",
#     "qa engineer",
#     "sdet",
#     "software quality analyst engineer",
#     "test automation",
#     "quality assurance",
#     "quality engineer",
#     "automation engineer",
#     "test automation",
#     "principal qa",
#     "qa lead",
#     "Software Development Engineer in Test II",
#     "senior automation engineer, quality assurance",
#     "automation tester",
#     "senior quality engineer",
#     "tester",
#     "performance engineer",
#     "performance tester",
#     "performance test engineer",
#     "performance automation engineer",
#     "performance automation tester",
#     "Quality Assurance & Automated Testing"
# ]

job_keywords = [
    "editor",
    "copy editor",
    "copyeditor",
    "proofreader",
    "sub-editor",
    "managing editor",
    "senior editor",
    "associate editor",
    "assistant editor",
    "editorial manager",
    "editorial lead",
    "content editor",
    "content manager",
    "content lead",
    "content strategist",
    "publishing editor",
    "commissioning editor",
    "acquisitions editor",
    "developmental editor",
    "production editor",
    "language editor",
    "english editor",
    "technical editor",
    "academic editor",
    "journal editor",
    "education editor",
    "curriculum editor",
    "learning content editor",
    "instructional editor",
    "instructional designer",
    "learning designer",
    "education content specialist",
    "editorial assistant",
    "editorial coordinator",
    "editorial director",
    "head of editorial",
    "publishing manager",
    "publishing coordinator",
    "publishing specialist",
    "writer-editor",
    "copywriter",
    "senior copywriter",
    "content writer",
    "education writer",
    "academic writer",
    "curriculum writer",
    "assessment writer",
    "learning materials developer",
    "educational content developer"
]
